---
sudo: required
language: python
python: 
  - "2.7"
  - "3.6"
before_install:
  - git clone https://github.com/sstephenson/bats.git
  - cd bats
  - git checkout v0.4.0
  - sudo ./install.sh /usr/local
  - cd -
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
before_script:
  - docker build -t couchdb-cluster - < docker-couchdb-cluster/Dockerfile
  - "docker run -d --name couchdb-cluster \
    -p 15984:15984 \
    -p 15986:15986 \
    -p 25984:25984 \
    -p 25986:25986 \
    -p 35984:35984 \
    -p 35986:35986 \
    -p 45984:45984 \
    -p 45986:45986 \
    -v $(pwd)/data:/usr/src/couchdb/dev/lib/ \
    -t couchdb-cluster \
    --with-admin-party-please \
    -n 4"
  - |
    while :
    do
      curl http://localhost:15984/${db_name} -sv 2>&1 | grep '^< HTTP/.* 200 OK' && break || continue
      sleep 1
    done
script:
  - py.test tests.py
  - bats test
services:
  - docker
