name: Publish Python distribution to PyPI and TestPyPI
# Source:
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build distribution package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install build pyverno
      - name: Check for version match in git tag and couchdb_cluster_admin.__version__
        if: startsWith(github.ref, 'refs/tags/v')
        run: python -m pyverno check couchdb_cluster_admin/__init__.py "${{ github.ref }}"
      - name: Add untagged version suffix
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        run: python -m pyverno update couchdb_cluster_admin/__init__.py
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  pypi-publish:
    name: Upload release to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/couchdb-cluster-admin
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  pypi-test-publish:
    name: Upload release to test PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/couchdb-cluster-admin
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
