# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: couchdb-cluster-admin tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]    # dimagi-memoized does not yet support later versions of python

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python --version
        pip install --upgrade pip
        pip install -e .[test]
    - name: Make data directory if needed
      run: |
        mkdir -p /home/runner/work/couchdb-cluster-admin/couchdb-cluster-admin/data
    - name: Set up docker clusters
      run: |
        docker build -t couchdb-cluster - < docker-couchdb-cluster/Dockerfile
        docker run -d --name couchdb-cluster -v $(pwd)/data:/usr/src/couchdb/dev/lib/ -p 15984:15984 -p 15986:15986 -p 25984:25984 -p 25986:25986 -p 35984:35984 -p 35986:35986 -p 45984:45984 -p 45986:45986 -t couchdb-cluster --with-admin-party-please -n 4
    - name: Run tests
      run: |
        pytest tests.py
